spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: spring
    password: spring
    driverClassName: com.mysql.jdbc.Driver
  hadoop:
    fsUri: hdfs://borneo:8020
    resourceManagerHost: borneo
    jobHistoryAddress: borneo:10020
    